# Script for populating the database. You can run it as:
#
#     mix run priv/repo/seeds.exs
#
# Inside the script, you can read and write to any of your
# repositories directly:
#
#     Tarot.Repo.insert!(%Tarot.SomeSchema{})
#
# We recommend using the bang functions (`insert!`, `update!`
# and so on) as they will fail if something goes wrong.

Tarot.Repo.insert!(%Tarot.Card{deck: "arcani_maggiori", name: "il matto", image: "00_il_matto", value: 0, suit: ""})
Tarot.Repo.insert!(%Tarot.Card{deck: "arcani_maggiori", name: "il bagatto", image: "01_il_bagatto", value: 1, suit: ""})
Tarot.Repo.insert!(%Tarot.Card{deck: "arcani_maggiori", name: "la papessa", image: "02_la_papessa", value: 2, suit: ""})
Tarot.Repo.insert!(%Tarot.Card{deck: "arcani_maggiori", name: "l'imperatrice", image: "03_l_imperatrice", value: 3, suit: ""})
Tarot.Repo.insert!(%Tarot.Card{deck: "arcani_maggiori", name: "l'imperatore", image: "04_l_imperatore", value: 4, suit: ""})
Tarot.Repo.insert!(%Tarot.Card{deck: "arcani_maggiori", name: "il papa", image: "05_il_papa", value: 5, suit: ""})
Tarot.Repo.insert!(%Tarot.Card{deck: "arcani_maggiori", name: "l'innamorato", image: "06_l_innamorato", value: 6, suit: ""})
Tarot.Repo.insert!(%Tarot.Card{deck: "arcani_maggiori", name: "il carro", image: "07_il_carro", value: 7, suit: ""})
Tarot.Repo.insert!(%Tarot.Card{deck: "arcani_maggiori", name: "la giustizia", image: "08_la_giustizia", value: 8, suit: ""})
Tarot.Repo.insert!(%Tarot.Card{deck: "arcani_maggiori", name: "l'eremita", image: "09_l_eremita", value: 9, suit: ""})
Tarot.Repo.insert!(%Tarot.Card{deck: "arcani_maggiori", name: "la ruota della fortuna", image: "10_la_ruota_della_fortuna", value: 10, suit: ""})
Tarot.Repo.insert!(%Tarot.Card{deck: "arcani_maggiori", name: "la forza", image: "11_la_forza", value: 11, suit: ""})
Tarot.Repo.insert!(%Tarot.Card{deck: "arcani_maggiori", name: "l'appeso", image: "12_l_appeso", value: 12, suit: ""})
Tarot.Repo.insert!(%Tarot.Card{deck: "arcani_maggiori", name: "la morte", image: "13_la_morte", value: 13, suit: ""})
Tarot.Repo.insert!(%Tarot.Card{deck: "arcani_maggiori", name: "la temperanza", image: "14_la_temperanza", value: 14, suit: ""})
Tarot.Repo.insert!(%Tarot.Card{deck: "arcani_maggiori", name: "il diavolo", image: "15_il_diavolo", value: 15, suit: ""})
Tarot.Repo.insert!(%Tarot.Card{deck: "arcani_maggiori", name: "la torre", image: "16_la_torre", value: 16, suit: ""})
Tarot.Repo.insert!(%Tarot.Card{deck: "arcani_maggiori", name: "le stelle", image: "17_le_stelle", value: 17, suit: ""})
Tarot.Repo.insert!(%Tarot.Card{deck: "arcani_maggiori", name: "la luna", image: "18_la_luna", value: 18, suit: ""})
Tarot.Repo.insert!(%Tarot.Card{deck: "arcani_maggiori", name: "il sole", image: "19_il_sole", value: 19, suit: ""})
Tarot.Repo.insert!(%Tarot.Card{deck: "arcani_maggiori", name: "il giudizio", image: "20_il_giudizio", value: 20, suit: ""})
Tarot.Repo.insert!(%Tarot.Card{deck: "arcani_maggiori", name: "il mondo", image: "21_il_mondo", value: 21, suit: ""})

Tarot.Repo.insert!(%Tarot.Card{deck: "arcani_minori", name: "asso di bastoni", image: "bastoni_01", value: 1, suit: "bastoni"})
Tarot.Repo.insert!(%Tarot.Card{deck: "arcani_minori", name: "2 di bastoni", image: "bastoni_02", value: 2, suit: "bastoni"})
Tarot.Repo.insert!(%Tarot.Card{deck: "arcani_minori", name: "3 di bastoni", image: "bastoni_03", value: 3, suit: "bastoni"})
Tarot.Repo.insert!(%Tarot.Card{deck: "arcani_minori", name: "4 di bastoni", image: "bastoni_04", value: 4, suit: "bastoni"})
Tarot.Repo.insert!(%Tarot.Card{deck: "arcani_minori", name: "5 di bastoni", image: "bastoni_05", value: 5, suit: "bastoni"})
Tarot.Repo.insert!(%Tarot.Card{deck: "arcani_minori", name: "6 di bastoni", image: "bastoni_06", value: 6, suit: "bastoni"})
Tarot.Repo.insert!(%Tarot.Card{deck: "arcani_minori", name: "7 di bastoni", image: "bastoni_07", value: 7, suit: "bastoni"})
Tarot.Repo.insert!(%Tarot.Card{deck: "arcani_minori", name: "8 di bastoni", image: "bastoni_08", value: 8, suit: "bastoni"})
Tarot.Repo.insert!(%Tarot.Card{deck: "arcani_minori", name: "9 di bastoni", image: "bastoni_09", value: 9, suit: "bastoni"})
Tarot.Repo.insert!(%Tarot.Card{deck: "arcani_minori", name: "10 di bastoni", image: "bastoni_10", value: 10, suit: "bastoni"})
Tarot.Repo.insert!(%Tarot.Card{deck: "arcani_minori", name: "fante di bastoni", image: "bastoni_11", value: 11, suit: "bastoni"})
Tarot.Repo.insert!(%Tarot.Card{deck: "arcani_minori", name: "cavaliere di bastoni", image: "bastoni_12", value: 12, suit: "bastoni"})
Tarot.Repo.insert!(%Tarot.Card{deck: "arcani_minori", name: "regina di bastoni", image: "bastoni_13", value: 13, suit: "bastoni"})
Tarot.Repo.insert!(%Tarot.Card{deck: "arcani_minori", name: "re di bastoni", image: "bastoni_14", value: 14, suit: "bastoni"})

Tarot.Repo.insert!(%Tarot.Card{deck: "arcani_minori", name: "asso di coppe", image: "coppe_01", value: 1, suit: "coppe"})
Tarot.Repo.insert!(%Tarot.Card{deck: "arcani_minori", name: "2 di coppe", image: "coppe_02", value: 2, suit: "coppe"})
Tarot.Repo.insert!(%Tarot.Card{deck: "arcani_minori", name: "3 di coppe", image: "coppe_03", value: 3, suit: "coppe"})
Tarot.Repo.insert!(%Tarot.Card{deck: "arcani_minori", name: "4 di coppe", image: "coppe_04", value: 4, suit: "coppe"})
Tarot.Repo.insert!(%Tarot.Card{deck: "arcani_minori", name: "5 di coppe", image: "coppe_05", value: 5, suit: "coppe"})
Tarot.Repo.insert!(%Tarot.Card{deck: "arcani_minori", name: "6 di coppe", image: "coppe_06", value: 6, suit: "coppe"})
Tarot.Repo.insert!(%Tarot.Card{deck: "arcani_minori", name: "7 di coppe", image: "coppe_07", value: 7, suit: "coppe"})
Tarot.Repo.insert!(%Tarot.Card{deck: "arcani_minori", name: "8 di coppe", image: "coppe_08", value: 8, suit: "coppe"})
Tarot.Repo.insert!(%Tarot.Card{deck: "arcani_minori", name: "9 di coppe", image: "coppe_09", value: 9, suit: "coppe"})
Tarot.Repo.insert!(%Tarot.Card{deck: "arcani_minori", name: "10 di coppe", image: "coppe_10", value: 10, suit: "coppe"})
Tarot.Repo.insert!(%Tarot.Card{deck: "arcani_minori", name: "fante di coppe", image: "coppe_11", value: 11, suit: "coppe"})
Tarot.Repo.insert!(%Tarot.Card{deck: "arcani_minori", name: "cavaliere di coppe", image: "coppe_12", value: 12, suit: "coppe"})
Tarot.Repo.insert!(%Tarot.Card{deck: "arcani_minori", name: "regina di coppe", image: "coppe_13", value: 13, suit: "coppe"})
Tarot.Repo.insert!(%Tarot.Card{deck: "arcani_minori", name: "re di coppe", image: "coppe_14", value: 14, suit: "coppe"})

Tarot.Repo.insert!(%Tarot.Card{deck: "arcani_minori", name: "asso di denari", image: "denari_01", value: 1, suit: "denari"})
Tarot.Repo.insert!(%Tarot.Card{deck: "arcani_minori", name: "2 di denari", image: "denari_02", value: 2, suit: "denari"})
Tarot.Repo.insert!(%Tarot.Card{deck: "arcani_minori", name: "3 di denari", image: "denari_03", value: 3, suit: "denari"})
Tarot.Repo.insert!(%Tarot.Card{deck: "arcani_minori", name: "4 di denari", image: "denari_04", value: 4, suit: "denari"})
Tarot.Repo.insert!(%Tarot.Card{deck: "arcani_minori", name: "5 di denari", image: "denari_05", value: 5, suit: "denari"})
Tarot.Repo.insert!(%Tarot.Card{deck: "arcani_minori", name: "6 di denari", image: "denari_06", value: 6, suit: "denari"})
Tarot.Repo.insert!(%Tarot.Card{deck: "arcani_minori", name: "7 di denari", image: "denari_07", value: 7, suit: "denari"})
Tarot.Repo.insert!(%Tarot.Card{deck: "arcani_minori", name: "8 di denari", image: "denari_08", value: 8, suit: "denari"})
Tarot.Repo.insert!(%Tarot.Card{deck: "arcani_minori", name: "9 di denari", image: "denari_09", value: 9, suit: "denari"})
Tarot.Repo.insert!(%Tarot.Card{deck: "arcani_minori", name: "10 di denari", image: "denari_10", value: 10, suit: "denari"})
Tarot.Repo.insert!(%Tarot.Card{deck: "arcani_minori", name: "fante di denari", image: "denari_11", value: 11, suit: "denari"})
Tarot.Repo.insert!(%Tarot.Card{deck: "arcani_minori", name: "cavaliere di denari", image: "denari_12", value: 12, suit: "denari"})
Tarot.Repo.insert!(%Tarot.Card{deck: "arcani_minori", name: "regina di denari", image: "denari_13", value: 13, suit: "denari"})
Tarot.Repo.insert!(%Tarot.Card{deck: "arcani_minori", name: "re di denari", image: "denari_14", value: 14, suit: "denari"})

Tarot.Repo.insert!(%Tarot.Card{deck: "arcani_minori", name: "asso di spade", image: "spade_01", value: 1, suit: "spade"})
Tarot.Repo.insert!(%Tarot.Card{deck: "arcani_minori", name: "2 di spade", image: "spade_02", value: 2, suit: "spade"})
Tarot.Repo.insert!(%Tarot.Card{deck: "arcani_minori", name: "3 di spade", image: "spade_03", value: 3, suit: "spade"})
Tarot.Repo.insert!(%Tarot.Card{deck: "arcani_minori", name: "4 di spade", image: "spade_04", value: 4, suit: "spade"})
Tarot.Repo.insert!(%Tarot.Card{deck: "arcani_minori", name: "5 di spade", image: "spade_05", value: 5, suit: "spade"})
Tarot.Repo.insert!(%Tarot.Card{deck: "arcani_minori", name: "6 di spade", image: "spade_06", value: 6, suit: "spade"})
Tarot.Repo.insert!(%Tarot.Card{deck: "arcani_minori", name: "7 di spade", image: "spade_07", value: 7, suit: "spade"})
Tarot.Repo.insert!(%Tarot.Card{deck: "arcani_minori", name: "8 di spade", image: "spade_08", value: 8, suit: "spade"})
Tarot.Repo.insert!(%Tarot.Card{deck: "arcani_minori", name: "9 di spade", image: "spade_09", value: 9, suit: "spade"})
Tarot.Repo.insert!(%Tarot.Card{deck: "arcani_minori", name: "10 di spade", image: "spade_10", value: 10, suit: "spade"})
Tarot.Repo.insert!(%Tarot.Card{deck: "arcani_minori", name: "fante di spade", image: "spade_11", value: 11, suit: "spade"})
Tarot.Repo.insert!(%Tarot.Card{deck: "arcani_minori", name: "cavaliere di spade", image: "spade_12", value: 12, suit: "spade"})
Tarot.Repo.insert!(%Tarot.Card{deck: "arcani_minori", name: "regina di spade", image: "spade_13", value: 13, suit: "spade"})
Tarot.Repo.insert!(%Tarot.Card{deck: "arcani_minori", name: "re di spade", image: "spade_14", value: 14, suit: "spade"})
